#include <ffigen/generate/generator/function_map_generator.hpp>
#include <iostream>

namespace ffigen
{
    //! converts
    //!
    //! int my_function(params...)
    //!
    //! to
    //!
    //! _library.my_function = [_library.int, [params...]];
    void function_map_generator::operator()(std::ostream & os) const
    {
        os << "_library." << entity.name() << " = [";
        os << entity.return_type().ffi_reference();
        os << ", [";

        bool is_first = true;
        for (code_entity const& parameter : entity.argument_types())
        {
            if (is_first)
            {
                is_first = false;
            }
            else
            {
                os << ", ";
            }
            os << parameter.ffi_reference();
        }

        os << "]];";
        newline(os);
        newline(os);
    }
}

// TODO: there are special keywords generated by node-ffi-generator. if a type is named after it, we have to skip mapping it.
//       special keywords are 'exports', 'module', 'require', '_library', ...
